<%
  @path = "#{RAILS_ROOT}/config/database.yml"
%>

<%= RAILS_ENV %>:
  adapter: mysql
  database: <%= rubber_env.db_name %>
  username: <%= rubber_env.db_user %>
  password: <%= rubber_env.db_pass %>
  host: <%= rubber_instances.for_role('db', 'primary' => true).first.full_name %>
